name: lint

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    timeout-minutes: 30
    name: "lint"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0-rc.1'
          check-latest: true
          cache: false

     - name: Get week number
        id: get-week
        run: echo "date=$(/bin/date -u "+%Y%V")" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/golangci-lint
          key: golangci-lint.cache-${{ env.ImageOS }}-go${{ steps.setup-go.go-version }}-${{ steps.get-week.outputs.date }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golangci-lint.cache-${{ env.ImageOS }}-go${{ steps.setup-go.go-version }}-${{ steps.get-week.outputs.date }}-
            golangci-lint.cache-${{ env.ImageOS }}-go${{ steps.setup-go.go-version }}-
            golangci-lint.cache-${{ env.ImageOS }}-
            golangci-lint.cache-

      - name: Code quality test (Linux)
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          skip-cache: true

      - name: Code quality test (Windows)
        uses: golangci/golangci-lint-action@v5
        env:
          GOOS: "windows"
        with:
          version: latest
          skip-cache: true

      - name: Code quality test (macOS)
        uses: golangci/golangci-lint-action@v5
        env:
          GOOS: "darwin"
        with:
          version: latest
          skip-cache: true

      - name: Code quality test (FreeBSD)
        uses: golangci/golangci-lint-action@v5
        env:
          GOOS: "freebsd"
        with:
          version: latest
          skip-cache: true

      - name: Code quality test (OpenBSD)
        uses: golangci/golangci-lint-action@v5
        env:
          GOOS: "openbsd"
        with:
          version: latest
          skip-cache: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Scan for vulnerabilities
        run: govulncheck ./...
